services:
  api:
    build: .
    container_name: suport-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run start:dev